id = test
name = Test Features
description = Just for testing the system and new features
requiredModules = common, philipshue, amazonpolly, immerse, sparrenburcht

---

#pete says "Welcome to the adventure" at speakers 1,2

dim all lights to 10
color all lights to white
wait 2 seconds
color light box to blue and dim to 100 in 5 seconds &
color light bank to red and dim to 100 in 5 seconds
#dim all lights to 100 in 4 seconds


#color light box to blue
#wait 2 seconds
#turn off all lights
#wait 2 seconds
#color lights bank,bureau to red
#wait 2 seconds
#dim all lights to 70
#color lights box,bank,bureau to green
