id = test
name = Test Features
description = Just for testing the system and new features
requiredModules = common, philipshue, amazonpolly, immerse, sparrenburcht

---

play clapping at speakers 1

play background music lala

#pete says "Hello this is a test message that will be moving from speaker 1 to speaker 2" moving on path (0,0,0);(40,0,0) with speed 10 with listener at location (20,50,0)

#play clapping.wav at volume 50 moving on path (0,0,0);(40,0,0) with speed 10.0 with listener at location (20,50,0) repeat 3 times

#play clapping.wav at volume 50 moving on path (0,0,0);(0,10,0) with speed 2.0 with listener circling around (0,0,0) with radius 10.0 with speed 15.0 as all speakers for 10 seconds


#play background music spiral.wav
#pete says "Welcome to the adventure" at speakers 1,2
#wait 2 seconds
#play clapping.wav at volume 100
#play clapping.wav at volume 25
#wait 2 seconds
#stop background music

#pete says "Welcome to the adventure" at speakers 1,2
#play clapping.wav at speaker 1 at volume 40
#play clapping.wav at location 50,0,0

#pete says "Welcome to the adventure" at speakers 1,2
#wait 1 seconds
#play background music chill.wav
#wait 2 seconds
#pete says "Someone talks during background music" at speakers 1,2 &
#color light bureau to white and dim to 0
#color light bureau to red and dim to 100 in 5 seconds
#wait 2 seconds
#stop background music
#turn off light bureau
#wait 2 seconds
#pete says "This is the end of the adventure" at speakers 1,2

#dim light bureau to 10
#wait 1 seconds
#set property default-transition-time to 2000
#dim light bureau to 100
#wait 1 seconds
#set property default-transition-time to 10000
#dim light bureau to 10

#dim all lights to 10
#color all lights to white
#wait 2 seconds
#color light box to blue and dim to 100 in 5 seconds &
#color light bank to red and dim to 100 in 5 seconds
#dim all lights to 100 in 4 seconds


#color light box to blue
#wait 2 seconds
#turn off all lights
#wait 2 seconds
#color lights bank,bureau to red
#wait 2 seconds
#dim all lights to 70
#color lights box,bank,bureau to green
