id = demo
name = Demo
description = Set the scene with a suspense introduction
requiredModules = common, philipshue, amazonpolly, immerse, sparrenburcht
type = SCENE

---

# It's very early in the morning, dawn is hardly visible
dim all lights to 0 in 0 seconds &
color all lights to white in 0 seconds &

wait 1 seconds

# Mysterious music plays in the background
play background music tension.wav at volume 40 with 3 seconds fade in

wait 2 seconds

play rain.wav at volume 80 with 3 seconds fade in save as rain &

wait 3 seconds

dim all lights to 100 in 0 seconds &
play lightning.wav &
wait 500 millis
dim all lights to 0 in 0 seconds &

wait 2 seconds

play thunder.wav for 3 seconds &

wait 1 seconds

dim all lights to 30 in 0 seconds &
wait 200 millis
dim all lights to 0 in 0 seconds &

stop playing rain with 3 seconds fade out

stop background music with 3 seconds fade out &

dim all lights to 50 in 10 seconds &

wait 2 seconds

play birds.wav at volume 80 with 3 seconds fade in for 6 seconds &

wait 3 seconds

play rooster.wav

wait 1 seconds

play background music medieval.wav at volume 25 with 3 seconds fade in

wait 2 seconds

narrator says "Welcome to Pine Castle!" at volume 100 &

wait 5 seconds

stop background music

