id = demo
name = Demo
description = Set the scene with a suspense introduction
requiredModules = common, philipshue, amazonpolly, immerse, sparrenburcht

---

# It's very early in the morning, dawn is hardly visible
dim all lights to 0 in 0 seconds &
color all lights to white in 0 seconds &

wait 1 seconds

# Mysterious music plays in the background
play background music tension.wav at volume 50

wait 1 seconds

play rain.wav at volume 100 with 3 seconds fade in for 8 seconds &

wait 3 seconds

dim all lights to 100 in 0 seconds &
play lightning.wav &
wait 500 millis
dim all lights to 0 in 0 seconds &

wait 2 seconds

play thunder.wav for 3 seconds &

wait 1 seconds

dim all lights to 30 in 0 seconds &
wait 200 millis
dim all lights to 0 in 0 seconds &

wait 1 seconds

stop background music

dim all lights to 50 in 10 seconds &

wait 1 seconds

play birds.wav for 5 seconds &

wait 3 seconds

play rooster.wav

wait 1 seconds

play background music medieval.wav

wait 2 seconds

narrator says "Welcome to Pine Castle!" at volume 100 &

wait 5 seconds

stop background music

