id = dragonattack
name = Dragon Attack
description = Light effects of the dragon attack
requiredModules = common, philipshue
type = EFFECT

---

dim all lights to 10 in 0 seconds
color all lights to green in 0 seconds
wait 100 millis

dim all lights to 100 in 1 seconds
color all lights to red in 1 seconds
dim all lights to 10 in 1 seconds
color all lights to green in 1 seconds

start script dragonattack
